apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxcnode-pv1
  labels:
    app: mysqldata1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 12Gi
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxcnode-pv2
  labels:
    app: mysqldata2
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 12Gi
 
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxcnode-pv3
  labels:
    app: mysqldata3
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 12Gi

 
